package com.iso.config;

import java.util.HashMap;
import java.util.Map;

public class Isov93Constant {

	private Isov93Constant() {

	}

	public static final String RESERVEDPRIVATE = "Reserved Private";
	public static final String RESERVEDISOUSE = "Reserved for ISO use";
	public static final String RESERVEDNATIONALUSE = "Reserved for national use";
	public static final String RESERVEDPRIVATEUSE = "Reserved for private use";

	public static final Map<Integer, Integer> isoFieldSizeMap() {
		Map<Integer, Integer> isoFieldSizeMap = new HashMap<>();
		isoFieldSizeMap.put(1, 128);
		isoFieldSizeMap.put(2, 19);
		isoFieldSizeMap.put(3, 6);
		isoFieldSizeMap.put(4, 12);
		isoFieldSizeMap.put(5, 12);
		isoFieldSizeMap.put(6, 12);
		isoFieldSizeMap.put(7, 10);
		isoFieldSizeMap.put(8, 8);
		isoFieldSizeMap.put(9, 8);
		isoFieldSizeMap.put(10, 8);
		isoFieldSizeMap.put(11, 12);
		isoFieldSizeMap.put(12, 12);
		isoFieldSizeMap.put(13, 4);
		isoFieldSizeMap.put(14, 4);
		isoFieldSizeMap.put(15, 4);
		isoFieldSizeMap.put(16, 4);
		isoFieldSizeMap.put(17, 4);
		isoFieldSizeMap.put(18, 4);
		isoFieldSizeMap.put(19, 3);
		isoFieldSizeMap.put(20, 3);
		isoFieldSizeMap.put(21, 3);
		isoFieldSizeMap.put(22, 3);
		isoFieldSizeMap.put(23, 3);
		isoFieldSizeMap.put(24, 3);
		isoFieldSizeMap.put(25, 2);
		isoFieldSizeMap.put(26, 2);
		isoFieldSizeMap.put(27, 1);
		isoFieldSizeMap.put(28, 8);
		isoFieldSizeMap.put(29, 8);
		isoFieldSizeMap.put(30, 8);
		isoFieldSizeMap.put(31, 8);
		isoFieldSizeMap.put(32, 11);
		isoFieldSizeMap.put(33, 11);
		isoFieldSizeMap.put(34, 28);
		isoFieldSizeMap.put(35, 37);
		isoFieldSizeMap.put(36, 104);
		isoFieldSizeMap.put(37, 12);
		isoFieldSizeMap.put(38, 6);
		isoFieldSizeMap.put(39, 3);
		isoFieldSizeMap.put(40, 3);
		isoFieldSizeMap.put(41, 3);
		isoFieldSizeMap.put(42, 15);
		isoFieldSizeMap.put(43, 40);
		isoFieldSizeMap.put(44, 25);
		isoFieldSizeMap.put(45, 76);
		isoFieldSizeMap.put(46, 999);
		isoFieldSizeMap.put(47, 999);
		isoFieldSizeMap.put(48, 999);
		isoFieldSizeMap.put(49, 3);
		isoFieldSizeMap.put(50, 3);
		isoFieldSizeMap.put(51, 3);
		isoFieldSizeMap.put(52, 16);
		isoFieldSizeMap.put(53, 18);
		isoFieldSizeMap.put(54, 120);
		isoFieldSizeMap.put(55, 999);
		isoFieldSizeMap.put(56, 999);
		isoFieldSizeMap.put(57, 999);
		isoFieldSizeMap.put(58, 999);
		isoFieldSizeMap.put(59, 999);
		isoFieldSizeMap.put(60, 7);
		isoFieldSizeMap.put(61, 999);
		isoFieldSizeMap.put(62, 999);
		isoFieldSizeMap.put(63, 999);
		isoFieldSizeMap.put(64, 16);
		isoFieldSizeMap.put(65, 16);
		isoFieldSizeMap.put(66, 1);
		isoFieldSizeMap.put(67, 2);
		isoFieldSizeMap.put(68, 3);
		isoFieldSizeMap.put(69, 3);
		isoFieldSizeMap.put(70, 3);
		isoFieldSizeMap.put(71, 8);
		isoFieldSizeMap.put(72, 8);
		isoFieldSizeMap.put(73, 6);
		isoFieldSizeMap.put(74, 10);
		isoFieldSizeMap.put(75, 10);
		isoFieldSizeMap.put(76, 10);
		isoFieldSizeMap.put(77, 10);
		isoFieldSizeMap.put(78, 10);
		isoFieldSizeMap.put(79, 10);
		isoFieldSizeMap.put(80, 10);
		isoFieldSizeMap.put(81, 10);
		isoFieldSizeMap.put(82, 12);
		isoFieldSizeMap.put(83, 12);
		isoFieldSizeMap.put(84, 12);
		isoFieldSizeMap.put(85, 12);
		isoFieldSizeMap.put(86, 15);
		isoFieldSizeMap.put(87, 15);
		isoFieldSizeMap.put(88, 15);
		isoFieldSizeMap.put(89, 15);
		isoFieldSizeMap.put(90, 42);
		isoFieldSizeMap.put(91, 1);
		isoFieldSizeMap.put(92, 2);
		isoFieldSizeMap.put(93, 5);
		isoFieldSizeMap.put(94, 7);
		isoFieldSizeMap.put(95, 42);
		isoFieldSizeMap.put(96, 8);
		isoFieldSizeMap.put(97, 16);
		isoFieldSizeMap.put(98, 25);
		isoFieldSizeMap.put(99, 11);
		isoFieldSizeMap.put(100, 11);
		isoFieldSizeMap.put(101, 17);
		isoFieldSizeMap.put(102, 28);
		isoFieldSizeMap.put(103, 28);
		isoFieldSizeMap.put(104, 100);
		isoFieldSizeMap.put(105, 999);
		isoFieldSizeMap.put(106, 999);
		isoFieldSizeMap.put(107, 999);
		isoFieldSizeMap.put(108, 999);
		isoFieldSizeMap.put(109, 999);
		isoFieldSizeMap.put(110, 999);
		isoFieldSizeMap.put(111, 999);
		isoFieldSizeMap.put(112, 999);
		isoFieldSizeMap.put(113, 11);
		isoFieldSizeMap.put(114, 999);
		isoFieldSizeMap.put(115, 999);
		isoFieldSizeMap.put(116, 999);
		isoFieldSizeMap.put(117, 999);
		isoFieldSizeMap.put(118, 999);
		isoFieldSizeMap.put(119, 999);
		isoFieldSizeMap.put(120, 999);
		isoFieldSizeMap.put(121, 999);
		isoFieldSizeMap.put(122, 999);
		isoFieldSizeMap.put(123, 999);
		isoFieldSizeMap.put(124, 255);
		isoFieldSizeMap.put(125, 999);
		isoFieldSizeMap.put(126, 6);
		isoFieldSizeMap.put(127, 999);
		isoFieldSizeMap.put(128, 16);

		return isoFieldSizeMap;
	}

	public static final Map<Integer, String> isoFieldNameMap() {
		Map<Integer, String> isoFieldNameMap = new HashMap<>();
		isoFieldNameMap.put(1, "Bit Map Extended");
		isoFieldNameMap.put(2, "Primary account number (PAN)");
		isoFieldNameMap.put(3, "Processing code");
		isoFieldNameMap.put(4, "Amount, transaction");
		isoFieldNameMap.put(5, "Amount, Settlement");
		isoFieldNameMap.put(6, "Amount, cardholder billing");
		isoFieldNameMap.put(7, "Transmission date & time");
		isoFieldNameMap.put(8, "Amount, Cardholder billing fee");
		isoFieldNameMap.put(9, "Conversion rate, Settlement");
		isoFieldNameMap.put(10, "Conversion rate, cardholder billing");
		isoFieldNameMap.put(11, "Systems trace audit number");
		isoFieldNameMap.put(12, "Time, Local transaction");
		isoFieldNameMap.put(13, "Date, Local transaction");
		isoFieldNameMap.put(14, "Date, Expiration");
		isoFieldNameMap.put(15, "Date, Settlement");
		isoFieldNameMap.put(16, "Date, conversion");
		isoFieldNameMap.put(17, "Date, capture");
		isoFieldNameMap.put(18, "Merchant type");
		isoFieldNameMap.put(19, "Acquiring institution country code");
		isoFieldNameMap.put(20, "PAN Extended, country code");
		isoFieldNameMap.put(21, "Forwarding institution. country code");
		isoFieldNameMap.put(22, "Point of service entry mode");
		isoFieldNameMap.put(23, "Application PAN number");
		isoFieldNameMap.put(24, "Network International identifier");
		isoFieldNameMap.put(25, "Point of service condition code");
		isoFieldNameMap.put(26, "Point of service capture code");
		isoFieldNameMap.put(27, "Authorising identification response length");
		isoFieldNameMap.put(28, "Amount, transaction fee");
		isoFieldNameMap.put(29, "Amount. settlement fee");
		isoFieldNameMap.put(30, "Amount, transaction processing fee");
		isoFieldNameMap.put(31, "Amount, settlement processing fee");
		isoFieldNameMap.put(32, "Acquiring institution identification code");
		isoFieldNameMap.put(33, "Forwarding institution identofication code");
		isoFieldNameMap.put(34, "Primary account number, extended");
		isoFieldNameMap.put(35, "Track 2 data");
		isoFieldNameMap.put(36, "Track 3 data");
		isoFieldNameMap.put(37, "Retrieval reference number");
		isoFieldNameMap.put(38, "Authorisation identification response");
		isoFieldNameMap.put(39, "Response code");
		isoFieldNameMap.put(40, "Service restriction code");
		isoFieldNameMap.put(41, "Card acceptor terminal identification");
		isoFieldNameMap.put(42, "Card acceptor identification code");
		isoFieldNameMap.put(43, "Card acceptor name/location");
		isoFieldNameMap.put(44, "Additional response data");
		isoFieldNameMap.put(45, "Track 1 Data");
		isoFieldNameMap.put(46, "Additional data - ISO");
		isoFieldNameMap.put(47, "Additional data - National");
		isoFieldNameMap.put(48, "Additional data - Private");
		isoFieldNameMap.put(49, "Currency code, transaction");
		isoFieldNameMap.put(50, "Currency code, settlement");
		isoFieldNameMap.put(51, "Currency code, cardholder billing");
		isoFieldNameMap.put(52, "Personal Identification number data");
		isoFieldNameMap.put(53, "Security related control information");
		isoFieldNameMap.put(54, "Additional amounts");
		isoFieldNameMap.put(55, "Reserved ISO");
		isoFieldNameMap.put(56, "Reserved ISO");
		isoFieldNameMap.put(57, "Reserved National");
		isoFieldNameMap.put(58, "Reserved National");
		isoFieldNameMap.put(59, RESERVEDNATIONALUSE);
		isoFieldNameMap.put(60, "Advice/reason code (private reserved)");
		isoFieldNameMap.put(61, RESERVEDPRIVATE);
		isoFieldNameMap.put(62, RESERVEDPRIVATE);
		isoFieldNameMap.put(63, RESERVEDPRIVATE);
		isoFieldNameMap.put(64, "Message authentication code (MAC)");
		isoFieldNameMap.put(65, "Bit map, tertiary");
		isoFieldNameMap.put(66, "Settlement code");
		isoFieldNameMap.put(67, "Extended payment code");
		isoFieldNameMap.put(68, "Receiving institution country code");
		isoFieldNameMap.put(69, "Settlement institution county code");
		isoFieldNameMap.put(70, "Network management Information code");
		isoFieldNameMap.put(71, "Message number");
		isoFieldNameMap.put(72, "Message number, last");
		isoFieldNameMap.put(73, "Date, Action");
		isoFieldNameMap.put(74, "Credits, number");
		isoFieldNameMap.put(75, "Credits, reversal number");
		isoFieldNameMap.put(76, "Debits, number");
		isoFieldNameMap.put(77, "Debits, reversal number");
		isoFieldNameMap.put(78, "Transfer number");
		isoFieldNameMap.put(79, "Transfer, reversal number");
		isoFieldNameMap.put(80, "Inquiries number");
		isoFieldNameMap.put(81, "Authorisations, number");
		isoFieldNameMap.put(82, "Credits, processsing fee amount");
		isoFieldNameMap.put(83, "Credits, transaction fee amount");
		isoFieldNameMap.put(84, "Debits, processing fee amount");
		isoFieldNameMap.put(85, "Debits, transaction fee amount");
		isoFieldNameMap.put(86, "Credits, amount");
		isoFieldNameMap.put(87, "Credits, reversal amount");
		isoFieldNameMap.put(88, "Debits, amount");
		isoFieldNameMap.put(89, "Debits, reversal amount");
		isoFieldNameMap.put(90, "Original data elements");
		isoFieldNameMap.put(91, "File update code");
		isoFieldNameMap.put(92, "File security code");
		isoFieldNameMap.put(93, "Response indicator");
		isoFieldNameMap.put(94, "Service indicator");
		isoFieldNameMap.put(95, "Replacement amounts");
		isoFieldNameMap.put(96, "Message security code");
		isoFieldNameMap.put(97, "Amount, net settlement");
		isoFieldNameMap.put(98, "Payee");
		isoFieldNameMap.put(99, "Settlement institution identification code");
		isoFieldNameMap.put(100, "Receiving institution identification code");
		isoFieldNameMap.put(101, "File name");
		isoFieldNameMap.put(102, "Account identification 1");
		isoFieldNameMap.put(103, "Account identification 2");
		isoFieldNameMap.put(104, "Transaction description");
		isoFieldNameMap.put(105, RESERVEDISOUSE);
		isoFieldNameMap.put(106, RESERVEDISOUSE);
		isoFieldNameMap.put(107, RESERVEDISOUSE);
		isoFieldNameMap.put(108, RESERVEDISOUSE);
		isoFieldNameMap.put(109, RESERVEDISOUSE);
		isoFieldNameMap.put(110, RESERVEDISOUSE);
		isoFieldNameMap.put(111, RESERVEDISOUSE);
		isoFieldNameMap.put(112, RESERVEDNATIONALUSE);
		isoFieldNameMap.put(113, "Authorising agent institution id code");
		isoFieldNameMap.put(114, RESERVEDNATIONALUSE);
		isoFieldNameMap.put(115, RESERVEDNATIONALUSE);
		isoFieldNameMap.put(116, RESERVEDNATIONALUSE);
		isoFieldNameMap.put(117, RESERVEDNATIONALUSE);
		isoFieldNameMap.put(118, RESERVEDNATIONALUSE);
		isoFieldNameMap.put(119, RESERVEDNATIONALUSE);
		isoFieldNameMap.put(120, RESERVEDPRIVATEUSE);
		isoFieldNameMap.put(121, RESERVEDPRIVATEUSE);
		isoFieldNameMap.put(122, RESERVEDPRIVATEUSE);
		isoFieldNameMap.put(123, RESERVEDPRIVATEUSE);
		isoFieldNameMap.put(124, "Info Text");
		isoFieldNameMap.put(125, "Network management information");
		isoFieldNameMap.put(126, "Issuer trace id");
		isoFieldNameMap.put(127, RESERVEDPRIVATEUSE);
		isoFieldNameMap.put(128, "Message Authentication code");
		return isoFieldNameMap;
	}

	public static final Map<Integer, IsoType> isoFieldTypeMap() {
		Map<Integer, IsoType> isoFieldTypeMap = new HashMap<>();
		isoFieldTypeMap.put(1, IsoType.FIXED);
		isoFieldTypeMap.put(2, IsoType.LLVAR);
		isoFieldTypeMap.put(3, IsoType.FIXED);
		isoFieldTypeMap.put(4, IsoType.FIXED);
		isoFieldTypeMap.put(5, IsoType.FIXED);
		isoFieldTypeMap.put(6, IsoType.FIXED);
		isoFieldTypeMap.put(7, IsoType.FIXED);
		isoFieldTypeMap.put(8, IsoType.FIXED);
		isoFieldTypeMap.put(9, IsoType.FIXED);
		isoFieldTypeMap.put(10, IsoType.FIXED);
		isoFieldTypeMap.put(11, IsoType.FIXED);
		isoFieldTypeMap.put(12, IsoType.FIXED);
		isoFieldTypeMap.put(13, IsoType.FIXED);
		isoFieldTypeMap.put(14, IsoType.FIXED);
		isoFieldTypeMap.put(15, IsoType.FIXED);
		isoFieldTypeMap.put(16, IsoType.FIXED);
		isoFieldTypeMap.put(17, IsoType.FIXED);
		isoFieldTypeMap.put(18, IsoType.FIXED);
		isoFieldTypeMap.put(19, IsoType.FIXED);
		isoFieldTypeMap.put(20, IsoType.FIXED);
		isoFieldTypeMap.put(21, IsoType.FIXED);
		isoFieldTypeMap.put(22, IsoType.FIXED);
		isoFieldTypeMap.put(23, IsoType.FIXED);
		isoFieldTypeMap.put(24, IsoType.FIXED);
		isoFieldTypeMap.put(25, IsoType.FIXED);
		isoFieldTypeMap.put(26, IsoType.FIXED);
		isoFieldTypeMap.put(27, IsoType.FIXED);
		isoFieldTypeMap.put(28, IsoType.FIXED);
		isoFieldTypeMap.put(29, IsoType.FIXED);
		isoFieldTypeMap.put(30, IsoType.FIXED);
		isoFieldTypeMap.put(31, IsoType.FIXED);
		isoFieldTypeMap.put(32, IsoType.LLVAR);
		isoFieldTypeMap.put(33, IsoType.LLVAR);
		isoFieldTypeMap.put(34, IsoType.LLVAR);
		isoFieldTypeMap.put(35, IsoType.LLVAR);
		isoFieldTypeMap.put(36, IsoType.LLLVAR);
		isoFieldTypeMap.put(37, IsoType.FIXED);
		isoFieldTypeMap.put(38, IsoType.FIXED);
		isoFieldTypeMap.put(39, IsoType.FIXED);
		isoFieldTypeMap.put(40, IsoType.FIXED);
		isoFieldTypeMap.put(41, IsoType.FIXED);
		isoFieldTypeMap.put(42, IsoType.FIXED);
		isoFieldTypeMap.put(43, IsoType.FIXED);
		isoFieldTypeMap.put(44, IsoType.LLVAR);
		isoFieldTypeMap.put(45, IsoType.LLVAR);
		isoFieldTypeMap.put(46, IsoType.LLLVAR);
		isoFieldTypeMap.put(47, IsoType.LLLVAR);
		isoFieldTypeMap.put(48, IsoType.LLLVAR);
		isoFieldTypeMap.put(49, IsoType.FIXED);
		isoFieldTypeMap.put(50, IsoType.FIXED);
		isoFieldTypeMap.put(51, IsoType.FIXED);
		isoFieldTypeMap.put(52, IsoType.FIXED);
		isoFieldTypeMap.put(53, IsoType.FIXED);
		isoFieldTypeMap.put(54, IsoType.FIXED);
		isoFieldTypeMap.put(55, IsoType.LLLVAR);
		isoFieldTypeMap.put(56, IsoType.LLVAR);
		isoFieldTypeMap.put(57, IsoType.LLLVAR);
		isoFieldTypeMap.put(58, IsoType.LLLVAR);
		isoFieldTypeMap.put(59, IsoType.LLLVAR);
		isoFieldTypeMap.put(60, IsoType.LVAR);
		isoFieldTypeMap.put(61, IsoType.LLLVAR);
		isoFieldTypeMap.put(62, IsoType.LLLVAR);
		isoFieldTypeMap.put(63, IsoType.LLLVAR);
		isoFieldTypeMap.put(64, IsoType.FIXED);
		isoFieldTypeMap.put(65, IsoType.FIXED);
		isoFieldTypeMap.put(66, IsoType.FIXED);
		isoFieldTypeMap.put(67, IsoType.FIXED);
		isoFieldTypeMap.put(68, IsoType.FIXED);
		isoFieldTypeMap.put(69, IsoType.FIXED);
		isoFieldTypeMap.put(70, IsoType.FIXED);
		isoFieldTypeMap.put(71, IsoType.FIXED);
		isoFieldTypeMap.put(72, IsoType.LLLVAR);
		isoFieldTypeMap.put(73, IsoType.FIXED);
		isoFieldTypeMap.put(74, IsoType.FIXED);
		isoFieldTypeMap.put(75, IsoType.FIXED);
		isoFieldTypeMap.put(76, IsoType.FIXED);
		isoFieldTypeMap.put(77, IsoType.FIXED);
		isoFieldTypeMap.put(78, IsoType.FIXED);
		isoFieldTypeMap.put(79, IsoType.FIXED);
		isoFieldTypeMap.put(80, IsoType.FIXED);
		isoFieldTypeMap.put(81, IsoType.FIXED);
		isoFieldTypeMap.put(82, IsoType.FIXED);
		isoFieldTypeMap.put(83, IsoType.FIXED);
		isoFieldTypeMap.put(84, IsoType.FIXED);
		isoFieldTypeMap.put(85, IsoType.FIXED);
		isoFieldTypeMap.put(86, IsoType.FIXED);
		isoFieldTypeMap.put(87, IsoType.FIXED);
		isoFieldTypeMap.put(88, IsoType.FIXED);
		isoFieldTypeMap.put(89, IsoType.FIXED);
		isoFieldTypeMap.put(90, IsoType.FIXED);
		isoFieldTypeMap.put(91, IsoType.FIXED);
		isoFieldTypeMap.put(92, IsoType.FIXED);
		isoFieldTypeMap.put(93, IsoType.FIXED);
		isoFieldTypeMap.put(94, IsoType.FIXED);
		isoFieldTypeMap.put(95, IsoType.FIXED);
		isoFieldTypeMap.put(96, IsoType.FIXED);
		isoFieldTypeMap.put(97, IsoType.FIXED);
		isoFieldTypeMap.put(98, IsoType.FIXED);
		isoFieldTypeMap.put(99, IsoType.LLVAR);
		isoFieldTypeMap.put(100, IsoType.LLVAR);
		isoFieldTypeMap.put(101, IsoType.FIXED);
		isoFieldTypeMap.put(102, IsoType.LLVAR);
		isoFieldTypeMap.put(103, IsoType.LLVAR);
		isoFieldTypeMap.put(104, IsoType.LLVAR);
		isoFieldTypeMap.put(105, IsoType.LLLVAR);
		isoFieldTypeMap.put(106, IsoType.LLLVAR);
		isoFieldTypeMap.put(107, IsoType.LLLVAR);
		isoFieldTypeMap.put(108, IsoType.LLLVAR);
		isoFieldTypeMap.put(109, IsoType.LLLVAR);
		isoFieldTypeMap.put(110, IsoType.LLLVAR);
		isoFieldTypeMap.put(111, IsoType.LLLVAR);
		isoFieldTypeMap.put(112, IsoType.LLLVAR);
		isoFieldTypeMap.put(113, IsoType.LLVAR);
		isoFieldTypeMap.put(114, IsoType.LLLVAR);
		isoFieldTypeMap.put(115, IsoType.LLLVAR);
		isoFieldTypeMap.put(116, IsoType.LLLVAR);
		isoFieldTypeMap.put(117, IsoType.LLLVAR);
		isoFieldTypeMap.put(118, IsoType.LLLVAR);
		isoFieldTypeMap.put(119, IsoType.LLLVAR);
		isoFieldTypeMap.put(120, IsoType.LLLVAR);
		isoFieldTypeMap.put(121, IsoType.LLLVAR);
		isoFieldTypeMap.put(122, IsoType.LLLVAR);
		isoFieldTypeMap.put(123, IsoType.LLLVAR);
		isoFieldTypeMap.put(124, IsoType.LLLVAR);
		isoFieldTypeMap.put(125, IsoType.LLLVAR);
		isoFieldTypeMap.put(126, IsoType.LLLVAR);
		isoFieldTypeMap.put(127, IsoType.LLLVAR);
		isoFieldTypeMap.put(128, IsoType.FIXED);
		return isoFieldTypeMap;
	}
}
